# Python Data Structure

### Primitive
- Integer
- String
- Float
- Boolean

### Non Primitive
- List
- Tuple
- Set
- Dictionary

____


# 1. Struktur Data List

Explore data struktur list

`[item1, item2, item3, item4, ...]`

In [1]:
myList = [0, 10, 41.5, "hello world", False]

In [2]:
type(myList)

list

In [3]:
dir(myList)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [4]:
help(myList.sort)

Help on built-in function sort:

sort(*, key=None, reverse=False) method of builtins.list instance
    Stable sort *IN PLACE*.



In [5]:
help(myList.clear)

Help on built-in function clear:

clear() method of builtins.list instance
    Remove all items from list.



#### Sifat Struktur Data List :
- heterogen

In [6]:
# beragam struktur data
myList = [ 10, 'hello', 14.5, False, [1, 3, 4]]

- akses seluruh elemen list

In [7]:
print(myList)

[10, 'hello', 14.5, False, [1, 3, 4]]


- akses 1 elemen pada list
- menggunakan positive index (dimulai dari index = 0 dari sisi kiri ujung)

In [8]:
myList[4]

[1, 3, 4]

In [9]:
myList[0]

10

In [10]:
myList[7]

IndexError: list index out of range

- menggunakan negative index (dimulai dari index = -1 dari sisi kanan ujung)

In [11]:
myList

[10, 'hello', 14.5, False, [1, 3, 4]]

In [12]:
myList[-1]

[1, 3, 4]

In [13]:
myList[-5]

10

In [14]:
myList[-7]

IndexError: list index out of range

- slicing pada list dengan menggunakan `myList[start_index : stop_index]`


In [20]:
myList

[10, 'hello', 14.5, False, [1, 3, 4]]

In [18]:
myList[0:4]

[10, 'hello', 14.5, False]

In [19]:
# jika start index tidak di define maka start_index = 0
myList[:4]

[10, 'hello', 14.5, False]

In [21]:
myList[:-1]

[10, 'hello', 14.5, False]

In [22]:
myList[-4:-2]

['hello', 14.5]

In [24]:
# jika stop index tidak di define maka stop_index = maximum index pada list
myList[1:]

['hello', 14.5, False, [1, 3, 4]]

In [25]:
myList

[10, 'hello', 14.5, False, [1, 3, 4]]

In [26]:
# kombinasi positive index dan negative index
myList[1:-1]

['hello', 14.5, False]

In [30]:
# menggunakan index diluar jangkauan list
myList[:7]

[10, 'hello', 14.5, False, [1, 3, 4]]

- start_index < stop_index (positive index/negative index)
- jika start index >= stop index , result list = []

In [31]:
myList[-3: -5]

[]

In [32]:
myList[4:1]

[]

In [33]:
myList[-3:-10]

[]

In [34]:
myList[:0]

[]

In [35]:
# menggunakan `:` tanpa mendefinisikan start dan stop index maka list akan di ambil seluruhnya
myList[:]

[10, 'hello', 14.5, False, [1, 3, 4]]

In [36]:
myList

[10, 'hello', 14.5, False, [1, 3, 4]]

- mengakses elemen list dalam list

In [38]:
# blok list terluar ditulis lebih dulu, diikuti blok list didalamnya,
myList[4]

[1, 3, 4]

In [39]:
myList[4][0]

1

In [40]:
myList[4][1:]

[3, 4]

In [41]:
myList[4][:-1]

[1, 3]

In [42]:
new_list = [1, 0.5, [11, ['hello', True, 1], 'test']]

In [43]:
# coba keluarkan item `hello`, `True`

In [44]:
new_list[2][1][0:2]

['hello', True]

- list bersifat **mutable**, sehingga kita bisa **reassign** dan **delete** elemen list

In [45]:
myList

[10, 'hello', 14.5, False, [1, 3, 4]]

In [46]:
myList[0] = 21

In [47]:
myList

[21, 'hello', 14.5, False, [1, 3, 4]]

- Value pada list yang reassign tidak harus satu tipe data

In [48]:
myList[3] = "Ganti ke string"

In [50]:
myList

[21, 'hello', 14.5, 'Ganti ke string', [1, 3, 4]]

In [51]:
myList[3] = False

In [52]:
myList

[21, 'hello', 14.5, False, [1, 3, 4]]

- Reassign multiple item (list) dengan menggunakan slice
- dimensi slice dengan list yang diinputkan sama

In [53]:
myList[0:2] = [33, 'world'] 

In [54]:
myList

[33, 'world', 14.5, False, [1, 3, 4]]

In [55]:
myList[0:2] = [False, 'hello']

In [56]:
myList

[False, 'hello', 14.5, False, [1, 3, 4]]

- dimensi yang diinputkan beda, 
- dimensi slice < dimensi list input

In [57]:
myList[0:2] = [33, 'world', 0, True] 

In [58]:
myList

[33, 'world', 0, True, 14.5, False, [1, 3, 4]]

- dimensi slice > dimensi list input

In [59]:
myList[0:4] = [10, 'hello']

In [61]:
myList

[10, 'hello', 14.5, False, [1, 3, 4]]

- delete item pada list
- item dengan index diatasnya akan mengisi index yang dihapus

In [62]:
del myList[0]

myList

['hello', 14.5, False, [1, 3, 4]]

- value `10` di remove, item `'hello'` menempati index 0, sebelumnya index 1, diikuti item lainya

- delete menggunakan slice

In [63]:
del myList[0:2]

myList

[False, [1, 3, 4]]

In [64]:
del myList[7]

IndexError: list assignment index out of range

In [65]:
del myList[4:7]

In [66]:
myList

[False, [1, 3, 4]]

#### Builtin function pada List

In [ ]:
help(myList.clear)

- builtin function pada list :

`append`, `clear`, `copy`, `count`, `extend`, `index`, `insert`, `pop`, `remove`, `reverse`, `sort`

- `append` : menambahkan item kedalam list, 
- posisi item yang ditambahkan pada list menempati index paling akhir

In [68]:
myList = [False, [1, 3, 4], 2, 3]

In [69]:
myList.append(3)

In [70]:
myList

[False, [1, 3, 4], 2, 3, 3]

In [71]:
myList.append('hello')

In [72]:
myList

[False, [1, 3, 4], 2, 3, 3, 'hello']

In [73]:
myList.append(4, 2)

TypeError: append() takes exactly one argument (2 given)

In [74]:
myList.append(['test', 'append'])

In [75]:
myList

[False, [1, 3, 4], 2, 3, 3, 'hello', ['test', 'append']]

In [76]:
# bagaimana caranya agar output seperti ini 
# [False, [1, 3, 4], 2, 3, 3, 'hello', ['test', 'append', 13]]

myList[6].append(13)

In [77]:
myList

[False, [1, 3, 4], 2, 3, 3, 'hello', ['test', 'append', 13]]

In [78]:
# bagaimana caranya agar output seperti ini 
# [False, [1, 3, 4, 'python'], 2, 3, 3, 'hello', ['test', 'append', 13]]

myList[1].append('python')

In [79]:
myList

[False, [1, 3, 4, 'python'], 2, 3, 3, 'hello', ['test', 'append', 13]]

- `count` : menghitung banyaknya item pada list dengan nilai yang diberikan

In [80]:
# mencari banyaknya item dengan nilai `14.5` pada list
myList.count('hello')

1

In [81]:
myList.append('hello')

In [82]:
myList

[False, [1, 3, 4, 'python'], 2, 3, 3, 'hello', ['test', 'append', 13], 'hello']

In [83]:
myList.count('hello')

2

- `insert` : menambahkan item kedalam list pada index tertentu

In [84]:
# menambahkan item = 3.14 kedalam list pada index = 1
myList.insert(1, 3.14)

myList

[False,
 3.14,
 [1, 3, 4, 'python'],
 2,
 3,
 3,
 'hello',
 ['test', 'append', 13],
 'hello']

- List yang menempati posisi yang diinsert akan terdorong ke-kanan,


- jika index pada `insert` > banyaknya index pada list, 
- maka item yang ditambahkan akan disimpan di akhir list

In [85]:
myList.insert(100, 'test out of range')

myList

[False,
 3.14,
 [1, 3, 4, 'python'],
 2,
 3,
 3,
 'hello',
 ['test', 'append', 13],
 'hello',
 'test out of range']

In [86]:
myList.insert(-79, 'test out of range')

myList

['test out of range',
 False,
 3.14,
 [1, 3, 4, 'python'],
 2,
 3,
 3,
 'hello',
 ['test', 'append', 13],
 'hello',
 'test out of range']

In [87]:
myList = [False, 3.14, [1, 3, 4], 2, 3, 3.14]

- `index` : mencari posisi item pada list, 
- jika lebih dari satu item ditemukan pada list, maka yang dikembalikan adalah yang pertama ditemukan

In [88]:
myList.index(False)

0

In [89]:
myList.index(3.14)

1

- mencari ukuran list

In [90]:
len(myList)

6

___
# 2. Struktur Data Matrix Numpy (Advance Structure)

*The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.* [(link)](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

![](resource/numpy.png)

- **Size** - Numpy data structures take up less space
- **Performance** - they have a need for speed and are faster than lists
- **Functionality** - SciPy and NumPy have optimized functions such as linear algebra operations built in.

Download **Numpy Cheat Sheet** from datacamp [(Download)](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

- install library numpy

In [91]:
! pip install numpy

- import library Numpy

In [93]:
import numpy as np

In [94]:
np.__version__

'1.19.1'

### Create 1D Vector

In [95]:
# vector baris (axis 0)

vector_row = np.array([1,2,3,4,5,6])

print(vector_row)


[1 2 3 4 5 6]


- Check dimesion of vector /matrix using `.shape`

In [96]:
print(vector_row.shape)

(6,)


In [97]:
type(vector_row)

numpy.ndarray

In [98]:
# vector kolom (axis 1)

vector_column = np.array([[1], [2], [3], [4], [5], [6]])

print(vector_column)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [99]:
print(vector_column.shape)

(6, 1)


### Create 2D Vector (Matrix)

In [100]:
matrix = np.array([[1,2,3,5],
                   [4,5,6,6],
                   [7,8,9,9]])
#[[1,2,3],
# [4,5,6]]

print(matrix)

[[1 2 3 5]
 [4 5 6 6]
 [7 8 9 9]]


In [101]:
matrix.shape

(3, 4)

In [102]:
type(matrix)

numpy.ndarray

### Create Matrix Zero
`np.zeros((3,4))` *Create an array of zeros*


In [103]:
zero_matrix = np.zeros(100)

print(zero_matrix)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [104]:
zero_matrix = np.zeros(6, 2)

print(zero_matrix)

TypeError: Cannot interpret '2' as a data type

In [105]:
zero_matrix = np.zeros((6, 2)) # 6 baris, 2 kolom

print(zero_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [106]:
zero_matrix = np.zeros((2, 6)) # 2 baris, 6 kolom

print(zero_matrix)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [107]:
zero_matrix = np.zeros((5, 7)) # 5 baris, 7 kolom

print(zero_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### Create Matrix One
`np.ones((2,3,4),dtype=np.int16)` *Create an array of ones*

In [108]:
one_matrix = np.ones(60)

print(one_matrix)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [109]:
one_matrix = np.ones((4, 9)) # 4 baris, 9 kolom

print(one_matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [110]:
one_matrix = np.ones((9, 4)) # 9 baris, 4 kolom

print(one_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [112]:
one_matrix = np.ones((10, 1))

print(one_matrix)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


### Akses elemen Vector

In [113]:
matrix

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [114]:
matrix[1] # akses baris index 1

array([4, 5, 6, 6])

In [115]:
matrix[-1] # akses baris index -1 (baris paling akhir)

array([7, 8, 9, 9])

- akses menggunakan slice

In [116]:
matrix[1:] # akses baris index 1 & 2

array([[4, 5, 6, 6],
       [7, 8, 9, 9]])

In [117]:
matrix[0:2] # akses baris index 0 & 1

array([[1, 2, 3, 5],
       [4, 5, 6, 6]])

In [118]:
matrix[-2:-1] # akses baris index 1 & 2

array([[4, 5, 6, 6]])

- mengakses kolom dalam matrix 2D

In [119]:
myList = [[1, 2, 3], [4, 5, 6]]

myList[0]

[1, 2, 3]

In [120]:
myList[0][1]

2

In [121]:
matrix

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [122]:
matrix[:, -1] # akses kolom index -1

array([5, 6, 9])

In [126]:
matrix[:, 2] # akses kolom index 1

array([3, 6, 9])

In [124]:
matrix[:, 2:] # akses kolom index 2 & 3 

array([[3, 5],
       [6, 6],
       [9, 9]])

In [125]:
matrix[:, 2:3]

array([[3],
       [6],
       [9]])

In [127]:
matrix #akses [5, 6, 6]

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [128]:
matrix[1, 1:]

array([5, 6, 6])

In [ ]:
#akses [[1, 2, 3]
#       [4, 5, 6]]

In [129]:
matrix[0:2, 0:3]

array([[1, 2, 3],
       [4, 5, 6]])

- Matrix 3D (baris, kolom, kedalaman)

In [130]:
matrix = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   
                   [[7, 8, 9],
                    [10,11,12]]])

In [131]:
matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [132]:
matrix[0] # akses baris ke 0

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
matrix[1] # akses baris ke 1

array([[ 7,  8,  9],
       [10, 11, 12]])

In [134]:
matrix[0, 1] # akses baris ke 0, kolom ke 1

array([4, 5, 6])

In [135]:
matrix[1, 1] # akses baris ke 1, kolom ke 1

array([10, 11, 12])

In [136]:
matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [137]:
matrix[1, 1, 1:] # akses baris ke 1, kolom ke 1, kedalaman ke 1 & 2

array([11, 12])

In [138]:
matrix[1, 1, 0:2] # akses baris ke 1, kolom ke 1, kedalaman ke 0 & 1

array([10, 11])

In [139]:
matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [140]:
# akses elemen [3, 6]
matrix[0, :, -1] # akses baris ke 0

array([3, 6])

In [141]:
# akses elemen [8, 11]
matrix[1, :, 1] # akses baris ke 0

array([ 8, 11])

In [142]:
# akses elemen [[1, 4], [7, 10]]
matrix[:, :, 0] # akses baris ke 0

array([[ 1,  4],
       [ 7, 10]])

In [ ]:
# akses elemen [[3, 6], [9, 12]]

In [143]:
matrix[:, :, -1]

array([[ 3,  6],
       [ 9, 12]])

- [Task] complex case **3D Matrix**, access elemen [9,9]

In [ ]:
matrix = np.array([[[1, 2, 3, 5, 5],
                    [4, 5, 6, 6, 6]],
                   
                   [[7, 8, 9, 9, 10],
                    [1, 3, 3, 1, 0 ]]])

In [ ]:
matrix.shape

In [ ]:
# jawaban


#

In [ ]:
matrix[1, 0, 2:4]

- [Task] complex case 3D Matrix, access elemen [1, 3, 3]

In [ ]:
# jawaban


#

In [ ]:
matrix[1, 1, :3]

### Vector Data Type

In [150]:
matrix = np.array([[ 1,  2,  3,  5,  5],
                   [ 4,  5,  6,  6,  6],
                   [ 7,  8,  9,  9, 10]])

In [151]:
matrix.dtype

dtype('int32')

In [152]:
matrix.nbytes

60

In [153]:
matrix = matrix.astype(np.uint16)

In [154]:
matrix.dtype

dtype('uint16')

In [155]:
matrix.nbytes

30

In [156]:
matrix = matrix.astype(np.int32)

In [157]:
matrix.dtype

dtype('int32')

In [158]:
matrix.nbytes

60

In [159]:
matrix = matrix.astype(np.uint8)

In [160]:
matrix.dtype

dtype('uint8')

In [161]:
matrix.nbytes

15

### Describe Vector

In [165]:
matrix = np.array([[ 1,  2,  3,  5,  5],
                   [ 4,  5,  6,  6,  6],
                   [ 7,  8,  9,  9, 10]])

In [166]:
matrix.shape # baris, kolom

(3, 5)

In [167]:
matrix.shape[0]

3

In [168]:
matrix.shape[1]

5

In [169]:
matrix.size

15

### Builtin Function

In [170]:
matrix

array([[ 1,  2,  3,  5,  5],
       [ 4,  5,  6,  6,  6],
       [ 7,  8,  9,  9, 10]])

In [171]:
np.max(matrix)

10

In [172]:
matrix.max()

10

In [173]:
np.min(matrix)

1

In [174]:
matrix.min()

1

In [175]:
np.mean(matrix)

5.733333333333333

In [176]:
matrix.mean()

5.733333333333333

In [177]:
np.median(matrix)

6.0

In [178]:
np.std(matrix)

2.515728301881761

In [179]:
matrix.std()

2.515728301881761

In [180]:
np.var(matrix)

6.328888888888889

In [181]:
matrix.var()

6.328888888888889

In [182]:
np.power(matrix, 3)

array([[   1,    8,   27,  125,  125],
       [  64,  125,  216,  216,  216],
       [ 343,  512,  729,  729, 1000]], dtype=int32)

In [183]:
np.sqrt(matrix)

array([[1.        , 1.41421356, 1.73205081, 2.23606798, 2.23606798],
       [2.        , 2.23606798, 2.44948974, 2.44948974, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.        , 3.16227766]])

In [184]:
matrix

array([[ 1,  2,  3,  5,  5],
       [ 4,  5,  6,  6,  6],
       [ 7,  8,  9,  9, 10]])

In [185]:
np.amax(matrix, axis=1) # 1 : kolom, 0 : baris

array([ 5,  6, 10])

In [186]:
np.amin(matrix, axis=1) # 1 : kolom, 0 : baris

array([1, 4, 7])

In [187]:
np.argmax(matrix, axis=1) # 1 : kolom, 0 : baris

array([3, 2, 4], dtype=int64)

In [188]:
np.argmin(matrix, axis=1) # 1 : kolom, 0 : baris

array([0, 0, 0], dtype=int64)

### Reshape Matrix

In [189]:
matrix = np.array([[1,2,3,5],
                   [4,5,6,6],
                   [7,8,9,9]])

print(matrix)

[[1 2 3 5]
 [4 5 6 6]
 [7 8 9 9]]


In [190]:
matrix.shape

(3, 4)

In [191]:
np.reshape(matrix, (4,3))

array([[1, 2, 3],
       [5, 4, 5],
       [6, 6, 7],
       [8, 9, 9]])

In [192]:
np.reshape(matrix, (3,2,2))

array([[[1, 2],
        [3, 5]],

       [[4, 5],
        [6, 6]],

       [[7, 8],
        [9, 9]]])

In [193]:
np.reshape(matrix, (12,1))

array([[1],
       [2],
       [3],
       [5],
       [4],
       [5],
       [6],
       [6],
       [7],
       [8],
       [9],
       [9]])

In [194]:
matrix 

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [195]:
np.reshape(matrix, (6,2))

array([[1, 2],
       [3, 5],
       [4, 5],
       [6, 6],
       [7, 8],
       [9, 9]])

### Matrix Operation

In [196]:
A = np.array([[1, 3, 1],
              [5, 2, 1]])

B = np.array([[0, 0, 1],
              [3, 5, 1]])

#### Penjumlahan Matrix

![](resource/penjumlahan_matrix.PNG)

In [197]:
A + B

array([[1, 3, 2],
       [8, 7, 2]])

In [198]:
A - B

array([[ 1,  3,  0],
       [ 2, -3,  0]])

#### Perkalian Skalar

![](resource/perkalian_scalar_matrix.PNG)

In [199]:
2 * A

array([[ 2,  6,  2],
       [10,  4,  2]])

In [200]:
3.5 * B

array([[ 0. ,  0. ,  3.5],
       [10.5, 17.5,  3.5]])

In [201]:
1 / A

array([[1.        , 0.33333333, 1.        ],
       [0.2       , 0.5       , 1.        ]])

In [202]:
mtr = np.array([0, 0])

1/mtr

C:\Users\yunus\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([inf, inf])

In [203]:
B / 2

array([[0. , 0. , 0.5],
       [1.5, 2.5, 0.5]])

#### Perkalian matrix biasa

$\begin{bmatrix} 1 & 3 & 1 \\ 5 & 2 & 1 \end{bmatrix} \begin{bmatrix} 0 & 0 & 1 \\ 3 & 5 & 1 \end{bmatrix} = \begin{bmatrix} 1\times0 & 1\times0 & 1\times1 \\ 5\times3 & 2\times5 & 1\times1 \end{bmatrix} = \begin{bmatrix} 0 & 0 & 1 \\ 15 & 10 & 1 \end{bmatrix}$

In [204]:
A*B

array([[ 0,  0,  1],
       [15, 10,  1]])

In [205]:
B/A

array([[0. , 0. , 1. ],
       [0.6, 2.5, 1. ]])

In [206]:
2 * B / A

array([[0. , 0. , 2. ],
       [1.2, 5. , 2. ]])

In [207]:
B**2

array([[ 0,  0,  1],
       [ 9, 25,  1]], dtype=int32)

#### Transpose Matrix

![](resource/transpose_matrix.PNG)

In [208]:
A

array([[1, 3, 1],
       [5, 2, 1]])

In [209]:
ATranspose = np.transpose(A)

ATranspose

array([[1, 5],
       [3, 2],
       [1, 1]])

In [210]:
np.transpose(ATranspose)

array([[1, 3, 1],
       [5, 2, 1]])

In [211]:
A.T

array([[1, 5],
       [3, 2],
       [1, 1]])

#### Matrix multiplication (dot product)

![](resource/dot_product.PNG)

- hanya dapat dilakukan jika dan hanya jika jumlah kolom pada matrix kiri sama dengan jumlah baris pada matrix kanan. \
$(M, n)(n, m)$ \
untuk, 
$(M, n)$ merupakan ukuran matrix dibagian kanan, \
$(n, m)$ merupakan ukuran matrix dibagian kiri, \
dan akan menghasilkan matrix dengan ukuran $(M, m)$


- Contoh :


$X = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$

- size X adalah 2, 3

$Y = \begin{bmatrix} 0 & 3 \\ 5 & 1 \\ 7 & 3\end{bmatrix}$

- size Y adalah 3, 2


- sehingga kedua matrix diatas dapat dilakukan operasi dot untuk size (2, `3`)(`3`, 2)


In [212]:
X = np.array([[1, 2, 1],
              [3, 0, 1]])

Y = np.array([[0, 3, 4, 1],
              [5, 1, 4, 1],
              [7, 3, 4, 1]])

In [213]:
X.shape, Y.shape

((2, 3), (3, 4))

In [216]:
np.dot(X, Y)

array([[17,  8, 16,  4],
       [ 7, 12, 16,  4]])

In [217]:
# (3,4)(2,3)
np.dot(Y, X)

ValueError: shapes (3,4) and (2,3) not aligned: 4 (dim 1) != 2 (dim 0)

In [218]:
# (3,4)(2,3)
np.dot(Y.T, X.T)

array([[17,  7],
       [ 8, 12],
       [16, 16],
       [ 4,  4]])

In [219]:
Y.T.shape, X.T.shape

((4, 3), (3, 2))