# Basic Numpy 

*The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.* [(link)](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

![](resource/numpy.png)

- **Size** - Numpy data structures take up less space
- **Performance** - they have a need for speed and are faster than lists
- **Functionality** - SciPy and NumPy have optimized functions such as linear algebra operations built in.

Download **Numpy Cheat Sheet** from datacamp [(Download)](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.1'

### Create 1D Vector

In [3]:
# vector baris (axis 0)

vector_row = np.array([1,2,3,4,5,6])

print(vector_row)


[1 2 3 4 5 6]


In [4]:
type(vector_row)

numpy.ndarray

- Check dimesion of vector /matrix using `.shape`

In [5]:
print(vector_row.shape)

(6,)


In [6]:
type(vector_row)

numpy.ndarray

In [7]:
# vector kolom (axis 1)

vector_column = np.array([[1],[2],[3], [4], [5], [6]])

print(vector_column)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [8]:
print(vector_column.shape)

(6, 1)


### Create 2D Vector (Matrix)

In [14]:
matrix = np.array([[1,2,3,5],
                   [4,5,6,5],
                   [7,8,9,9]])
#[[1,2,3],
# [4,5,6]]

print(matrix)

[[1 2 3 5]
 [4 5 6 5]
 [7 8 9 9]]


In [13]:
matrix.shape

(3,)

In [11]:
type(matrix)

numpy.ndarray

### Create Matrix Zero
`np.zeros((3,4))` *Create an array of zeros*


In [15]:
zero_matrix = np.zeros(100)

print(zero_matrix)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [16]:
zero_matrix.shape

(100,)

In [17]:
zero_matrix = np.zeros(6, 2)

print(zero_matrix)

TypeError: Cannot interpret '2' as a data type

In [18]:
zero_matrix = np.zeros((6, 2)) # 6 baris, 2 kolom

print(zero_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [19]:
zero_matrix = np.zeros((2, 6)) # 2 baris, 6 kolom

print(zero_matrix)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [20]:
zero_matrix = np.zeros((5, 7)) # 5 baris, 7 kolom

print(zero_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [21]:
zero_matrix = np.zeros((4, 5, 2)) # 4 baris, 5 kolom, 2 kedalaman

print(zero_matrix)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


### Create Matrix One
`np.ones((2,3,4),dtype=np.int16)` *Create an array of ones*

In [22]:
one_matrix = np.ones(60)

print(one_matrix)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [23]:
one_matrix = np.ones((4, 9)) # 4 baris, 9 kolom

print(one_matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [24]:
one_matrix = np.ones((9, 4)) # 9 baris, 4 kolom

print(one_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Generate Matrix
`np.linspace(0,2,9)` *Create an array of evenly*

In [28]:
generated_matrix = np.linspace(1,5)  # default 50 item, generate from 1 to 5

In [29]:
print(generated_matrix)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [31]:
generated_matrix = np.linspace(1,5,3)
print(generated_matrix)

[1. 3. 5.]


In [32]:
generated_matrix = np.linspace(1,5,5)
print(generated_matrix)

[1. 2. 3. 4. 5.]


In [33]:
generated_matrix = np.linspace(0,5,6)
print(generated_matrix)

[0. 1. 2. 3. 4. 5.]


In [34]:
generated_matrix = np.linspace(0,10,3)
print(generated_matrix)

[ 0.  5. 10.]


### Akses elemen Vector

In [35]:
matrix

array([[1, 2, 3, 5],
       [4, 5, 6, 5],
       [7, 8, 9, 9]])

In [36]:
matrix[1] # akses baris index 1

array([4, 5, 6, 5])

In [37]:
matrix[-1] # akses baris index -1 (baris paling akhir)

array([7, 8, 9, 9])

- akses menggunakan slice

In [38]:
matrix[1:] # akses baris index 1 & 2

array([[4, 5, 6, 5],
       [7, 8, 9, 9]])

In [39]:
matrix[0:2] # akses baris index 0 & 1

array([[1, 2, 3, 5],
       [4, 5, 6, 5]])

In [40]:
matrix[-2:-1] # akses baris index 1 & 2

array([[4, 5, 6, 5]])

- mengakses kolom dalam matrix 2D

In [41]:
myList = [[1, 2, 3], [4, 5, 6]]

myList[0]

[1, 2, 3]

In [42]:
myList[0][1]

2

In [43]:
matrix

array([[1, 2, 3, 5],
       [4, 5, 6, 5],
       [7, 8, 9, 9]])

In [44]:
matrix[:, -1] # akses kolom index -1

array([5, 5, 9])

In [45]:
matrix[:, 1] # akses kolom index 1

array([2, 5, 8])

In [46]:
matrix[:, 2:] # akses kolom index 2 & 3 

array([[3, 5],
       [6, 5],
       [9, 9]])

In [47]:
matrix[:, 2:3]

array([[3],
       [6],
       [9]])

In [48]:
matrix[:, 2] #akses [3, 6, 9]

array([3, 6, 9])

In [51]:
#akses 7, 8, 9, 9
matrix[2, ]

array([7, 8, 9, 9])

In [52]:
matrix

array([[1, 2, 3, 5],
       [4, 5, 6, 5],
       [7, 8, 9, 9]])

In [55]:
# akses 3, 5

matrix[0, 2:]

array([3, 5])

In [58]:
# akses 4, 5, 6
matrix[1, 0:3]

array([4, 5, 6])

In [60]:
# akses 8, 9, 9
matrix[2, 1:]

array([8, 9, 9])

- Matrix 3D (baris, kolom, kedalaman)

In [61]:
matrix = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   
                   [[7, 8, 9],
                    [10,11,12]]])

In [62]:
matrix[0] # akses baris ke 0

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
matrix[1] # akses baris ke 1

array([[ 7,  8,  9],
       [10, 11, 12]])

In [64]:
matrix[0, 1] # akses baris ke 0, kolom ke 1

array([4, 5, 6])

In [65]:
matrix[1, 1] # akses baris ke 1, kolom ke 1

array([10, 11, 12])

In [66]:
matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [67]:
matrix[1, 1, 1:] # akses baris ke 1, kolom ke 1, kedalaman ke 1 & 2

array([11, 12])

In [68]:
matrix[1, 1, 0:2] # akses baris ke 1, kolom ke 1, kedalaman ke 0 & 1

array([10, 11])

In [69]:
matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [70]:
# akses elemen [3, 6]
matrix[0, :, 2] # akses baris ke 0

array([3, 6])

In [71]:
# akses elemen [8, 11]
matrix[1, :, 1] # akses baris ke 0

array([ 8, 11])

In [72]:
# akses elemen [[1, 4], [7, 10]]
matrix[:, :, 0] # akses baris ke 0

array([[ 1,  4],
       [ 7, 10]])

In [73]:
# akses elemen [[3, 6], [9, 12]]
matrix[:,:,2]

array([[ 3,  6],
       [ 9, 12]])

In [74]:
matrix[:, :, -1]

array([[ 3,  6],
       [ 9, 12]])

- [Task] complex case **3D Matrix**, access elemen [9,9]

In [ ]:
matrix = np.array([[[1, 2, 3, 5, 5],
                    [4, 5, 6, 6, 6]],
                   
                   [[7, 8, 9, 9, 10],
                    [1, 3, 3, 1, 0 ]]])

In [ ]:
matrix.shape

In [ ]:
# jawaban


#

In [ ]:
matrix[1, 0, 2:4]

- [Task] complex case 3D Matrix, access elemen [1, 3, 3]

In [ ]:
# jawaban


#

In [ ]:
matrix[1, 1, :3]

### Vector Data Type

In [75]:
matrix = np.array([[ 1,  2,  3,  5,  5],
                   [ 4,  5,  6,  6,  6],
                   [ 7,  8,  9,  9, 10]])

In [76]:
matrix.dtype

dtype('int32')

In [77]:
matrix = matrix.astype(np.uint16)

In [78]:
matrix.dtype

dtype('uint16')

In [79]:
matrix.nbytes

30

In [80]:
matrix = matrix.astype(np.int32)

In [81]:
matrix.dtype

dtype('int32')

In [82]:
matrix.nbytes

60

In [83]:
matrix = matrix.astype(np.uint8)

In [84]:
matrix.dtype

dtype('uint8')

In [85]:
matrix.nbytes

15

In [86]:
matrix

array([[ 1,  2,  3,  5,  5],
       [ 4,  5,  6,  6,  6],
       [ 7,  8,  9,  9, 10]], dtype=uint8)

### Describe Vector

In [87]:
matrix = np.array([[ 1,  2,  3,  5,  5],
                   [ 4,  5,  6,  6,  6],
                   [ 7,  8,  9,  9, 10]])

In [88]:
matrix.shape # baris, kolom

(3, 5)

In [89]:
matrix.shape[0]

3

In [90]:
matrix.shape[1]

5

In [91]:
matrix.size

15

In [92]:
matrix.ndim

2

In [93]:
vec = np.array([1, 2, 3])

vec.ndim

1

### Builtin Function

In [94]:
matrix

array([[ 1,  2,  3,  5,  5],
       [ 4,  5,  6,  6,  6],
       [ 7,  8,  9,  9, 10]])

In [95]:
np.max(matrix)

10

In [96]:
matrix.max()

10

In [97]:
np.min(matrix)

1

In [98]:
matrix.min()

1

In [99]:
np.mean(matrix)

5.733333333333333

In [100]:
matrix.mean()

5.733333333333333

In [101]:
np.median(matrix)

6.0

In [104]:
np.std(matrix)

2.515728301881761

In [105]:
matrix.std()

2.515728301881761

In [106]:
np.var(matrix)

6.328888888888889

In [107]:
matrix.var()

6.328888888888889

In [108]:
np.power(matrix, 3)

array([[   1,    8,   27,  125,  125],
       [  64,  125,  216,  216,  216],
       [ 343,  512,  729,  729, 1000]], dtype=int32)

In [109]:
np.sqrt(matrix)

array([[1.        , 1.41421356, 1.73205081, 2.23606798, 2.23606798],
       [2.        , 2.23606798, 2.44948974, 2.44948974, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.        , 3.16227766]])

In [111]:
np.cbrt(matrix)

array([[1.        , 1.25992105, 1.44224957, 1.70997595, 1.70997595],
       [1.58740105, 1.70997595, 1.81712059, 1.81712059, 1.81712059],
       [1.91293118, 2.        , 2.08008382, 2.08008382, 2.15443469]])

In [112]:
matrix

array([[ 1,  2,  3,  5,  5],
       [ 4,  5,  6,  6,  6],
       [ 7,  8,  9,  9, 10]])

In [113]:
np.max(matrix)

10

In [114]:
np.amax(matrix)

10

In [116]:
np.amax(matrix, axis=0) # 1 : kolom, 0 : baris

array([ 7,  8,  9,  9, 10])

In [118]:
np.amin(matrix, axis=0) # 1 : kolom, 0 : baris

array([1, 2, 3, 5, 5])

In [120]:
np.argmax(matrix, axis=1) # 1 : kolom, 0 : baris

array([2, 2, 2, 2, 2], dtype=int64)

In [122]:
np.argmin(matrix, axis=0) # 1 : kolom, 0 : baris

array([0, 0, 0, 0, 0], dtype=int64)

### Reshape Matrix

In [123]:
matrix = np.array([[1,2,3,5],
                   [4,5,6,6],
                   [7,8,9,9]])

print(matrix)

[[1 2 3 5]
 [4 5 6 6]
 [7 8 9 9]]


In [124]:
matrix.shape

(3, 4)

In [130]:
np.reshape(matrix, (4,3))

array([[1, 2, 3],
       [5, 4, 5],
       [6, 6, 7],
       [8, 9, 9]])

In [126]:
np.reshape(matrix, (3,2,2))

array([[[1, 2],
        [3, 5]],

       [[4, 5],
        [6, 6]],

       [[7, 8],
        [9, 9]]])

In [127]:
np.reshape(matrix, (12,1))

array([[1],
       [2],
       [3],
       [5],
       [4],
       [5],
       [6],
       [6],
       [7],
       [8],
       [9],
       [9]])

In [128]:
matrix 

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [ ]:
np.reshape(matrix, (6,2))

### Matrix Operation

In [136]:
A = np.array([[1, 3, 1],
              [5, 2, 1]])

B = np.array([[0, 0, 1],
              [3, 5, 1]])

#### Penjumlahan Matrix

![](resource/penjumlahan_matrix.PNG)

In [137]:
A + B

array([[1, 3, 2],
       [8, 7, 2]])

In [138]:
A - B

array([[ 1,  3,  0],
       [ 2, -3,  0]])

#### Perkalian Skalar

![](resource/perkalian_scalar_matrix.PNG)

In [139]:
2 * A

array([[ 2,  6,  2],
       [10,  4,  2]])

In [140]:
3.5 * B

array([[ 0. ,  0. ,  3.5],
       [10.5, 17.5,  3.5]])

In [141]:
1 / A

array([[1.        , 0.33333333, 1.        ],
       [0.2       , 0.5       , 1.        ]])

In [143]:
mtr = np.array([0, 0])

1/mtr

C:\Users\yunus\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([inf, inf])

In [144]:
B / 2

array([[0. , 0. , 0.5],
       [1.5, 2.5, 0.5]])

#### Perkalian matrix biasa

$\begin{bmatrix} 1 & 3 & 1 \\ 5 & 2 & 1 \end{bmatrix} \begin{bmatrix} 0 & 0 & 1 \\ 3 & 5 & 1 \end{bmatrix} = \begin{bmatrix} 1\times0 & 1\times0 & 1\times1 \\ 5\times3 & 2\times5 & 1\times1 \end{bmatrix} = \begin{bmatrix} 0 & 0 & 1 \\ 15 & 10 & 1 \end{bmatrix}$

In [145]:
A*B

array([[ 0,  0,  1],
       [15, 10,  1]])

In [146]:
B/A

array([[0. , 0. , 1. ],
       [0.6, 2.5, 1. ]])

In [147]:
2 * B / A

array([[0. , 0. , 2. ],
       [1.2, 5. , 2. ]])

#### Transpose Matrix

![](resource/transpose_matrix.PNG)

In [148]:
A

array([[1, 3, 1],
       [5, 2, 1]])

In [149]:
ATranspose = np.transpose(A)

ATranspose

array([[1, 5],
       [3, 2],
       [1, 1]])

In [150]:
np.transpose(ATranspose)

array([[1, 3, 1],
       [5, 2, 1]])

In [151]:
A.T

array([[1, 5],
       [3, 2],
       [1, 1]])

#### Matrix multiplication (dot product)

![](resource/dot_product.PNG)

- hanya dapat dilakukan jika dan hanya jika jumlah kolom pada matrix kiri sama dengan jumlah baris pada matrix kanan. \
$(M, n)(n, m)$ \
untuk, 
$(M, n)$ merupakan ukuran matrix dibagian kanan, \
$(n, m)$ merupakan ukuran matrix dibagian kiri, \
dan akan menghasilkan matrix dengan ukuran $(M, m)$


- Contoh :


$X = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$

- size X adalah 2, 3

$Y = \begin{bmatrix} 0 & 3 \\ 5 & 1 \\ 7 & 3\end{bmatrix}$

- size Y adalah 3, 2


- sehingga kedua matrix diatas dapat dilakukan operasi dot untuk size (2, `3`)(`3`, 2)


In [152]:
X = np.array([[1, 2, 1],
              [3, 0, 1]])

Y = np.array([[0, 3, 4, 1],
              [5, 1, 4, 1],
              [7, 3, 4, 1]])

In [153]:
X.shape, Y.shape

((2, 3), (3, 4))

In [154]:
np.dot(X, Y)

array([[17,  8, 16,  4],
       [ 7, 12, 16,  4]])

In [155]:
# (3,4)(2,3)
np.dot(Y, X)

ValueError: shapes (3,4) and (2,3) not aligned: 4 (dim 1) != 2 (dim 0)

In [156]:
# (3,4)(2,3)
np.dot(Y.T, X.T)

array([[17,  7],
       [ 8, 12],
       [16, 16],
       [ 4,  4]])

In [157]:
Y.T.shape, X.T.shape

((4, 3), (3, 2))

### [Task]
- Buat dua buah 2D matrix (A & B) dengan ukuran masing-masing (4,5) dan (5, 2), dengan menggunakan `np.linspace` & `np.reshape`
- hitung A ⋅ B

In [ ]:
np.linspace(1,10,20)

In [ ]:
A = np.reshape(np.linspace(1,10,20), (4,5))

In [ ]:
A